before_install:
  - "sudo pip install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz"
  - "git clone --depth=50 https://github.com/jsdoc3/jsdoc build/jsdoc"
  - "git clone https://code.google.com/p/glsl-unit/ build/glsl-unit"

before_script:
  - "./build.py plovr"
  - "./build.py serve-integration-test &"
  - "rm src/ol/renderer/webgl/*shader.js"
  - "sleep 3"

script: "./build.py JSDOC=build/jsdoc/jsdoc integration-test"
